<a href="https://colab.research.google.com/github/recursingfeynman/dotfiles/blob/master/deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [91]:
import torch
import numpy as np

In [12]:
x = torch.empty(2,3,2,2,)
print(x)

tensor([[[[8.4455e-36, 0.0000e+00],
          [1.0930e-43, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00],
          [7.7052e+31, 1.9447e+31]]],


        [[[2.1715e-18, 2.3081e-12],
          [1.8590e+34, 7.7767e+31]],

         [[1.7181e+19, 1.8990e+28],
          [1.5766e-19, 1.4585e-19]],

         [[7.1856e+22, 1.8609e+34],
          [1.8179e+31, 1.8524e+28]]]])


In [14]:
torch.rand(2,2)

tensor([[0.8564, 0.8177],
        [0.2588, 0.5611]])

In [28]:
x = torch.rand(2,2, dtype = torch.float16)

In [29]:
x

tensor([[0.6475, 0.0698],
        [0.6724, 0.9907]], dtype=torch.float16)

In [ ]:
x = torch.rand(4,4)
y = torch.tensor([3,2])

print(x)
print(y)

# z = y @ x.T
print("\nResults:")
print(x.view(-1, 1))

In [101]:
a = torch.ones(5)
b = np.ones(5)

In [146]:
x = torch.randn(3, requires_grad=True)
print(x)

with torch.no_grad():
  y = x + 2
  print(y)

tensor([-0.8728, -0.5613, -0.4871], requires_grad=True)
tensor([1.1272, 1.4387, 1.5129])


In [152]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(5):
  model_output = (weights * 3).sum()

  model_output.backward()

  print(weights.grad)

  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
# Weights before next iteration -> add zero's
optimizer = torch.optim.SGD(weights, lr = 0.01)
optimizer.step()
optimizer.zero_grad()

In [156]:
### Backpropagation

x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

# Forward pass and compute loss

y_hat = w * x
loss = (y_hat - y) ** 2

print(loss)

# Backward pass

loss.backward()
print(w.grad)

# Update weights
# Next forward and backwards ...

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
